version: '3'
services:
  socialnetwork_mysql:
    container_name: bray-socialnetwork-mysql
    image: mysql:8.0
    ports:
      - 3360:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    healthcheck:
      test: [ "CMD", "mysqladmin", "--user=root", "--password=1234", "--host=127.0.0.1", "ping", "--silent" ]
      interval: 2s
      timeout: 10s
      retries: 10
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  socialnetwork_backend_php:
    container_name: bray-socialnetwork-backend-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8030:8030"
    volumes:
      - .:/app
    depends_on:
          - socialnetwork_mysql
    command: symfony serve --dir=apps/socialnetwork/backend/public --port=8030 --force-php-discovery