version: '3'
services:
  bray_socialnetwork_backend_php:
    container_name: bray-socialnetwork-backend-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8030:8030"
    volumes:
      - .:/app
    command: symfony serve --dir=apps/socialnetwork/backend/public --port=8030 --force-php-discovery