brays_get:
  path: /brays
  controller: Bray\Apps\Socialnetwork\Backend\Controller\Brays\BraysGetController
  methods:  [GET]

bray_put:
  path: /brays/{id}
  controller: Bray\Apps\Socialnetwork\Backend\Controller\Brays\BraysPutController
  methods:  [PUT]